jsh9/pydoclint

- CHANGELOG.md
- pydoclint/__init__.py
- pydoclint/main.py
A version info command line flag helps, especially with a project in such rapid development to be sure about which version is currently used.
This pull request adds a `__version__` attribute to the package and a `--version` option to the cli program. The version info is taken from `setup.cfg`.
> Add CLI option `--version` to show version info

- .pre-commit-config.yaml
- .pre-commit-hooks.yaml
- CHANGELOG.md
- README.md
Hey thanks for the cool project ❤️ 
Since I want to replace `darglint` in my `pre-commit` configs with your project (so tired of waiting on docs to lint) it would be nice to integrate it as a stand-alone hook rather than adding it to `flake8` (my current workaround). 
Especially since I want to replace `flake8` with `ruff` anyway and `darglint` was the last big blocker.
> ✨ Add ability to use as stand-alone pre-commit hook

- .github/.pre-commit-config-self-check.yaml
- .github/workflows/python-package.yml
- .pre-commit-config.yaml
- CHANGELOG.md
- pydoclint/main.py
- tests/data/common/non_ascii/non_ascii.py
- tests/test_main.py
- tox.ini
This change fixes two issues related to encoding on windows.
- A crash when using `pydoclint` as pre-commit hook due to console encoding (see #20)
- A crash when the source file contains no ASCII characters that can not be encoded using the localized system code page
In addition, I refactored the CI pipeline a bit using [`tox-gh-actions`](https://github.com/ymyzk/tox-gh-actions) to duplicate tox env execution.
Examples of the failing tests to reproduce the original issues on the CI can be found for [usage as pre-commit](https://github.com/s-weigand/pydoclint/actions/runs/5157330364/jobs/9289584540) and [file encoding](https://github.com/s-weigand/pydoclint/actions/runs/5156506653) on my fork.
closes #20
> 🩹 Fix windows encoding issues

- CHANGELOG.md
- pydoclint/utils/violation.py
The error code in the message passed to `flake8` should not end with `:` since this causes problems with tools like [`yesqa`](https://github.com/asottile/yesqa) that parse the `flake8` output.
E.g. this nonsense example
```py
def f(positive_nr: int):  # noqa: DOC502
"""Does something.
Parameters
----------
positive_nr : int
Used to do something
Raises
------
ValueError
If ``positive_nr`` is not a positive number.
"""
ensure_positive(positive_nr) # raise value error if positive_nr is not positive
result = ...
return result
```
In this case `yesqa` would remove the `noqa` since it sees the error code reported as `DOC502:` instead of `DOC502` (It uses flake8 formatting string `--format=%(row)d\t%(code)s`) which then does not match and the noqa gets removed.
> 🩹 Don't use colon after error code in message text for flake8

- README.md
This mentions darglint2 instead of only stating that darglint is no longer maintained.
> Link darglint2 in README.

- .editorconfig
- .github/workflows/python-package.yml
- .github/workflows/python-publish.yml
- .pre-commit-config.yaml
- .pre-commit-hooks.yaml
- .prettierrc.yaml
Since the exclude is only configured in pre-commit. Editors and prettier itself will format yaml files with proseWrap=always. This is a problem for YAML. So why not configure prettier and editors through .editorconfig correctly so that it can be used to enforce proper formatting of YAML files.
> Editorconfig and enable prettier for yaml

- CHANGELOG.md
- pydoclint/utils/return_anno.py
- setup.cfg
- tests/utils/test_return_anno.py
Fixes https://github.com/jsh9/pydoclint/issues/44
> Fix incorrect tuple annotation detection

- CHANGELOG.md
- pydoclint/flake8_entry.py
- setup.cfg
The argument was already defined, but never passed on to the AST visitor.
> Parse '--check-return-types' in flake8 plugin

- CHANGELOG.md
- docs/config_options.md
- docs/how_to_config.md
- pydoclint/flake8_entry.py
- pydoclint/main.py
- pydoclint/utils/return_yield_raise.py
- pydoclint/visitor.py
- pyproject.toml
- setup.cfg
- tests/data/google/no_return_section/cases.py
- tests/data/google/returning_noreturn/cases.py
- tests/data/numpy/no_return_section/cases.py
- tests/data/numpy/returning_noreturn/cases.py
- tests/data/sphinx/no_return_section/cases.py
- tests/data/sphinx/returning_noreturn/cases.py
- tests/test_main.py
When a function has a return type of `NoReturn` it means it will never return, so the documentation doesn't really need to specify a return.
The option `--require-return-section-when-returning-none` was renamed to `--require-return-section-when-returning-nothing` to highlight it is more generic now, as it will also require a returns section for `NoReturn`. The old option is kept as a deprecation error.
Fixes #55.
> Don't require a returns section for `NoReturn`

- CHANGELOG.md
- docs/how_to_ignore.md
- pydoclint/utils/arg.py
- setup.cfg
- tests/data/edge_cases/edge_case_02_syntax_error_in_type_hints.py
- tests/test_main.py
Fixes https://github.com/jsh9/pydoclint/issues/59
> Handle syntax errors in type hints

- CHANGELOG.md
- docs/violation_codes.md
- pydoclint/utils/violation.py
- setup.cfg
- tests/test_main.py
Fixes https://github.com/jsh9/pydoclint/issues/61
> Update broken URL on DOC103 notes

- CHANGELOG.md
- docs/notes_generator_vs_iterator.md
- pydoclint/utils/violation.py
- pydoclint/visitor.py
- tests/test_main.py
This PR addresses the user experience issue (i.e., lack of a dedicated violation code to inform users how to fix issues) in https://github.com/jsh9/pydoclint/issues/68
> Improve violation msg on Generator/Iterator

- CHANGELOG.md
- README.md
- docs/config_options.md
- docs/how_to_config.md
- docs/index.md
- pydoclint/baseline.py
- pydoclint/main.py
- setup.cfg
- tests/test_baseline.py
This PR experiment is about generating and checking errors using the baseline file.
I understand that I haven't written the tests yet. Please rate this PR as an idea.
> Baseline integration

- pydoclint/utils/arg.py
- pydoclint/visitor.py
- setup.cfg
- tests/data/edge_cases/06_no_type_hints_in_doc/numpy.py
- tests/test_main.py
Resolves https://github.com/jsh9/pydoclint/issues/85
> Don't check type hints for DOC103

- CHANGELOG.md
- pydoclint/utils/arg.py
- setup.cfg
- tests/data/edge_cases/05_escape_char/google.py
- tests/data/edge_cases/05_escape_char/numpy.py
- tests/data/edge_cases/05_escape_char/sphinx.py
- tests/utils/test_arg.py
Fixes https://github.com/jsh9/pydoclint/issues/92
> Fix prepended escape char handling

- docs/how_to_config.md
- docs/how_to_ignore.md
Upstreams knowledge from https://github.com/jsh9/pydoclint/issues/96
- That native mode doesn't support error codes
Resolves https://github.com/jsh9/pydoclint/issues/101
- Adds sample `pre-commit-config.yaml` for `flake8`-plugin, with configs
Also documents how to configure `ruff` compatibility using `external`
> Documenting tool integration

- pyproject.toml
- setup.cfg
- tox.ini
In CI, dependencies are installed to system Python. For developers, it's common to use a virtual environment named `venv` or `.venv`.  This PR adds ignores for those to `flake8` and `pydoclint`
> Exclude venv folders in flake8

- CHANGELOG.md
- docs/checking_class_attributes.md
- docs/config_options.md
- pydoclint/flake8_entry.py
- pydoclint/main.py
- pydoclint/utils/arg.py
- pydoclint/utils/doc.py
- pydoclint/utils/generic.py
- pydoclint/utils/violation.py
- pydoclint/utils/visitor_helper.py
- pydoclint/visitor.py
- pyproject.toml
- setup.cfg
- tests/data/google/class_attributes/cases.py
- tests/data/google/class_attributes/init_docstring.py
- tests/data/numpy/class_attributes/cases.py
- tests/data/numpy/class_attributes/init_docstring.py
- tests/data/sphinx/class_attributes/cases.py
- tests/data/sphinx/class_attributes/init_docstring.py
- tests/test_main.py
Closes https://github.com/jsh9/pydoclint/issues/122
> Check class attributes against docstring

- CHANGELOG.md
- docs/config_options.md
- pydoclint/flake8_entry.py
- pydoclint/main.py
- pydoclint/utils/visitor_helper.py
- pydoclint/visitor.py
- setup.cfg
- tests/data/edge_cases/12_property_methods_as_class_attr/google.py
- tests/test_main.py
Partially addresses https://github.com/jsh9/pydoclint/issues/148
> Add option to treat property methods as class attributes

- CHANGELOG.md
- docs/config_options.md
- pydoclint/flake8_entry.py
- pydoclint/main.py
- pydoclint/utils/arg.py
- pydoclint/utils/visitor_helper.py
- setup.cfg
- tests/data/edge_cases/12_property_methods_as_class_attr/google.py
- tests/data/edge_cases/13_class_attr_assignments/google.py
- tests/test_main.py
- tests/utils/test_visitor_helper.py
Address https://github.com/jsh9/pydoclint/issues/151
> Improve class attr comparison logic

- tox.ini
If a user is using `tox-uv` (a plugin for tox that supports running the various `pip` commands vi `uv`), then `pip install .` is seen as an external command, which would require `allowlist_externals`. Instead, install the local project by specifying it as a dep. Then, regular tox and tox-uv both will install it as `pip install .` or `uv pip install .`, respectively.
----
tested with `tox 4.16.0`, with and without `tox-uv-1.9.0` installed.
- https://github.com/tox-dev/tox-uv
> tox: use `deps = .` instead of `pip install`

- CHANGELOG.md
- docs/violation_codes.md
- pydoclint/utils/return_yield_raise.py
- pydoclint/utils/violation.py
- pydoclint/utils/visitor_helper.py
- pydoclint/utils/walk.py
- pydoclint/visitor.py
- setup.cfg
- tests/data/google/raises/cases.py
- tests/data/numpy/raises/cases.py
- tests/data/sphinx/raises/cases.py
- tests/test_main.py
- tests/utils/test_returns_yields_raise.py
- tests/utils/test_walk.py
Closes #158 
Compare any raise statements in function bodies to docstring Raises sections and ensures they match. Exceptions specified in a docstring are kept as a sorted list, so duplicate lines will throw DOC503 as well.
Had to introduce a new walker, `walk.walk_dfs`, but I did add tests for it.
This feature does NOT do any resolution of errors, so something like the following:
```
try:
1 / 0
except:
raise
```
will not identify any specific exceptions thrown. Similarly, `except Exception: raise` will expect `Exception` to be included in the docstring. I think both of those cases are already caught as style violations by certain ruff rules (probably under `BLE` or `TRY`?), so it might not be much of a problem.
----
While this checks names of exceptions it doesn't check order(?) like your …
> feat: introduce DOC503 for checking specific raised exceptions

- CHANGELOG.md
- pydoclint/utils/generic.py
- pydoclint/utils/return_yield_raise.py
- setup.cfg
- tests/data/google/raises/cases.py
- tests/data/numpy/raises/cases.py
- tests/data/sphinx/raises/cases.py
- tests/test_main.py
- tests/utils/test_returns_yields_raise.py
Previously, AST walking was not properly identifying the name of exceptions like `m.Exception`. Update logic for determining names from an AST to correctly get the whole name (as well as related tests).
Fixes #165 
Seems to work as expected on the minimal case provided in that issue. Can you think of other edge cases I've missed adding to the tests?
> fix: DOC503 catch namespaced exceptions

- docs/notes_for_users.md
Please make sure the wait for this Pull-Request to be merged, so that the documentation is ready once the built-in has been merged -> https://github.com/nvimtools/none-ls.nvim/pull/181
> doc(usage): Including a null-ls use with neovim.

- CHANGELOG.md
- pydoclint/utils/arg.py
- tests/data/edge_cases/16_assign_to_attr/cases.py
- tests/test_main.py
Fixes https://github.com/jsh9/pydoclint/issues/180
> Fix bug caused by assigning value to attr

- CHANGELOG.md
- pydoclint/utils/return_yield_raise.py
- setup.cfg
- tests/utils/test_returns_yields_raise.py
When code uses `raise <> as e` and then `raise e`, we previously were incorrectly yielding `e` (the `subnode.id`) rather than determining the originally-bound name of the exception. This introduces an additional check for AST nodes which look like an exception handler with a name binding.
----
closes #175
> fix: get name of a raised exception when bound in except

- .pre-commit-hooks.yaml
- CHANGELOG.md
- README.md
- docs/index.md
- setup.cfg
Since I want the inline ignore feature when running `pydoclint` via `flake8` I'm using a hook like so.
```yaml
- repo: https://github.com/PyCQA/flake8
rev: 7.1.1
hooks:
- id: flake8
alias: flake8-docs
args:
- "--select=DOC"
- "--extend-ignore=DOC502,DOC601,DOC603"
- "--color=always"
- "--require-return-section-when-returning-nothing=False"
- "--allow-init-docstring=True"
- "--skip-checking-short-docstrings=False"
name: "lint docstrings"
exclude: "^(docs/|tests?/)"
additional_dependencies: [pydoclint==0.5.6]
```
This has the obvious drawback that I manually need to look up the latest version of `pydoclint` and update it (If I don't forget the additional dependency, see how outdated it is 😥).
Having a `flake8` based hook in the `pydoclint` repo would allow me to easily keep up with the …
> 👌 Add pre-commit-hook to run pydoclint via flake8

- CHANGELOG.md
- pydoclint/utils/return_yield_raise.py
- pydoclint/visitor.py
- setup.cfg
- tests/data/edge_cases/23_bare_return_stmt_with_yield/google.py
- tests/test_main.py
- tests/utils/test_returns_yields_raise.py
Fixes https://github.com/jsh9/pydoclint/issues/126
> Fix false positive DOC405 & DOC201 for bare returns

- CHANGELOG.md
- docs/config_options.md
- docs/style_mismatch.md
- docs/violation_codes.md
- pydoclint/flake8_entry.py
- pydoclint/main.py
- pydoclint/utils/doc.py
- pydoclint/utils/parse_docstring.py
- pydoclint/utils/violation.py
- pydoclint/visitor.py
- setup.cfg
- tests/data/common/style_mismatch.py
- tests/test_main.py
Closes https://github.com/jsh9/pydoclint/issues/169 and https://github.com/jsh9/pydoclint/issues/196
> Add DOC003 to check docstring style mismatch

- .github/.pre-commit-config-self-check.yaml
- pyproject.toml
- setup.cfg
- setup.py
This reverts commit 54c368b7a6a5a94722155a13b2728c00f0f4c818.
> Revert "Migrate to pyproject.toml (#214)"

- CHANGELOG.md
- pydoclint/main.py
Closes https://github.com/jsh9/pydoclint/issues/212
> Throw error when user provides no paths

- CHANGELOG.md
- pydoclint/flake8_entry.py
- setup.cfg
Fixes https://github.com/jsh9/pydoclint/issues/208
> Fix missing config option onlyAttrsWithClassVarAreTreatedAsClassAttrs

- CHANGELOG.md
- pydoclint/main.py
- pydoclint/utils/arg.py
- setup.cfg
- tests/data/edge_cases/09_double_quotes/google.py
- tests/data/edge_cases/09_double_quotes/numpy.py
- tests/test_main.py
Fixes https://github.com/jsh9/pydoclint/issues/231 and https://github.com/jsh9/pydoclint/issues/233.
> Fix bug with double quotes; change "--quiet" default

- CHANGELOG.md
- pydoclint/main.py
Fixes https://github.com/jsh9/pydoclint/issues/237.
Reverts the changes in https://github.com/jsh9/pydoclint/pull/236 (which was to address https://github.com/jsh9/pydoclint/issues/233).
> Revert `--quiet` to default to `False`

- CHANGELOG.md
- docs/config_options.md
Fixes https://github.com/jsh9/pydoclint/issues/239
> Fix a typo in the documentation
