jsh9/pydoclint

CHANGELOG.md
README.md
pydoclint/utils/violation.py
pydoclint/visitor.py
tests/data/google/parsing_errors/cases.py
tests/data/numpy/parsing_errors/cases.py
tests/test_main.py

To address the issue raised here: https://github.com/jsh9/pydoclint/issues/3#issuecomment-1562606133

Add docstring parsing errors as DOC001

---

CHANGELOG.md
README.md
pydoclint/flake8_entry.py
pydoclint/main.py
pydoclint/utils/return_yield_raise.py
pydoclint/visitor.py
tests/data/google/no_return_section/cases.py
tests/data/numpy/no_return_section/cases.py
tests/test_main.py

This PR should fix https://github.com/jsh9/pydoclint/issues/6

Allow no return section in docstring

---

CHANGELOG.md
pydoclint/utils/generic.py
pydoclint/utils/return_yield_raise.py
pydoclint/visitor.py
tests/data/google/yields/cases.py
tests/data/numpy/yields/cases.py
tests/test_main.py

This PR closes https://github.com/jsh9/pydoclint/issues/15

Better identify generator methods

---

CHANGELOG.md
pydoclint/utils/return_yield_raise.py
tests/data/google/yields/cases.py
tests/data/numpy/yields/cases.py
tests/test_main.py

Fixes https://github.com/jsh9/pydoclint/issues/40

Fix false positive DOC402

---

CHANGELOG.md
pydoclint/main.py
pydoclint/utils/doc.py
setup.cfg
tests/data/sphinx/abstract_method/cases.py
tests/data/sphinx/allow_init_docstring/cases.py
tests/data/sphinx/args/classmethod.py
tests/data/sphinx/args/function.py
tests/data/sphinx/args/method.py
tests/data/sphinx/args/staticmethod.py
tests/data/sphinx/init/init.py
tests/data/sphinx/no_return_section/cases.py
tests/data/sphinx/parsing_errors/cases.py
tests/data/sphinx/property_method/cases.py
tests/data/sphinx/raises/cases.py
tests/data/sphinx/returning_none/cases.py
tests/data/sphinx/returns/classmethod.py
tests/data/sphinx/returns/function.py
tests/data/sphinx/returns/method.py
tests/data/sphinx/returns/staticmethod.py
tests/data/sphinx/short_docstrings/cases.py
tests/data/sphinx/star_args/cases.py
tests/data/sphinx/star_args/cases2.py
tests/data/sphinx/type_hints/cases.py
tests/data/sphinx/yields/cases.py
tests/test_main.py

This PR addresses https://github.com/jsh9/pydoclint/issues/43

Add support for Sphinx docstring style

---

CHANGELOG.md
pydoclint/utils/annotation.py
pydoclint/utils/arg.py
pydoclint/utils/generic.py
setup.cfg
tests/data/edge_cases/edge_case_01.py
tests/test_main.py
tests/utils/test_arg.py
tests/utils/test_generic.py

Fixes https://github.com/jsh9/pydoclint/issues/56

Improve type hint comparison algorithm

---

CHANGELOG.md
setup.cfg
tests/data/edge_cases/edge_case_03_union_return_type.py
tests/test_main.py

Fixes https://github.com/jsh9/pydoclint/issues/66

Fix union return type (Google style)

---

CHANGELOG.md
pydoclint/utils/generic.py

Fixes https://github.com/jsh9/pydoclint/issues/65

Deal with potential recursion error

---

CHANGELOG.md
pydoclint/utils/arg.py
setup.cfg
tests/data/edge_cases/05_escape_char/google.py
tests/data/edge_cases/05_escape_char/numpy.py
tests/data/edge_cases/05_escape_char/sphinx.py
tests/test_main.py
tests/utils/test_arg.py

Fixes https://github.com/jsh9/pydoclint/issues/73

Better handling of backslash in docstring

---

CHANGELOG.md
pydoclint/flake8_entry.py
pydoclint/main.py
pydoclint/utils/visitor_helper.py
pydoclint/visitor.py
setup.cfg
tests/data/google/no_return_section/cases.py
tests/data/google/no_yield_section/cases.py
tests/data/numpy/no_return_section/cases.py
tests/data/numpy/no_yield_section/cases.py
tests/data/playground.py
tests/data/sphinx/no_return_section/cases.py
tests/data/sphinx/no_yield_section/cases.py
tests/test_main.py

Fixes https://github.com/jsh9/pydoclint/issues/79

Do not require Yields section if yielding None

---

CHANGELOG.md
README.md
docs/index.md
setup.cfg

Addresses https://github.com/jsh9/pydoclint/issues/81

Make flake8 dependency optional

---

CHANGELOG.md
pydoclint/flake8_entry.py
pydoclint/main.py
pydoclint/visitor.py
tests/data/edge_cases/07_underscore_args/google.py
tests/data/edge_cases/07_underscore_args/google_with_violations.py
tests/data/edge_cases/07_underscore_args/numpy.py
tests/data/edge_cases/07_underscore_args/sphinx.py
tests/test_main.py

Closes https://github.com/jsh9/pydoclint/issues/87

Ignore underscore args when checking args

---

.pre-commit-hooks.yaml

Fixes https://github.com/jsh9/pydoclint/issues/91

Disable parallel mode in pre-commit

---

CHANGELOG.md
pydoclint/utils/generic.py
pydoclint/utils/visitor_helper.py
pyproject.toml
setup.cfg
tests/data/edge_cases/09_double_quotes_in_Literal/google.py
tests/data/edge_cases/09_double_quotes_in_Literal/numpy.py
tests/test_main.py
tests/utils/test_generic.py

Fix double quotes in Literal type hint

---

CHANGELOG.md
pydoclint/main.py
setup.cfg

Fixes https://github.com/jsh9/pydoclint/issues/117

Remove useless argument `--src`

---

CHANGELOG.md
pydoclint/utils/violation.py
setup.cfg
tests/data/edge_cases/10_absent_return_anno/numpy.py
tests/test_main.py

Fixes https://github.com/jsh9/pydoclint/issues/127

Improve DOC403 message

---

docs/checking_class_attributes.md

very minor edit, make url a proper link

Make url a proper link

---

CHANGELOG.md
pydoclint/utils/generic.py
setup.cfg
tests/data/edge_cases/15_very_long_annotations/google.py
tests/data/edge_cases/15_very_long_annotations/numpy.py
tests/data/edge_cases/15_very_long_annotations/sphinx.py
tests/test_main.py

Fixes https://github.com/jsh9/pydoclint/issues/164

Improve handling of long type annotations

---

CHANGELOG.md
pydoclint/main.py
pydoclint/parse_config.py

Closes https://github.com/jsh9/pydoclint/issues/166

Hide msg about loading config in quiet mode

---

CHANGELOG.md
docs/config_options.md
pydoclint/flake8_entry.py
pydoclint/main.py
pydoclint/utils/visitor_helper.py
pydoclint/visitor.py
tests/data/edge_cases/17_ClassVar/cases.py
tests/test_main.py
tests/utils/test_visitor_helper.py

Closes https://github.com/jsh9/pydoclint/issues/140

Add new config option to treat ClassVar attrs as class attrs

---

CHANGELOG.md
pydoclint/utils/arg.py
tests/data/edge_cases/18_assign_to_subscript/case.py
tests/test_main.py

Fixes https://github.com/jsh9/pydoclint/issues/190

Fix a bug with subscript assign

---

CHANGELOG.md
docs/config_options.md
pydoclint/baseline.py
pydoclint/main.py
pydoclint/utils/violation.py
setup.cfg
tests/test_baseline.py

Closes https://github.com/jsh9/pydoclint/issues/197

Add an option to auto regenerate baseline

---

.pre-commit-config.yaml
.pre_commit_helper_scripts/check_full_diff_in_changelog.py
CHANGELOG.md
docs/config_options.md
pydoclint/flake8_entry.py
pydoclint/main.py
pydoclint/visitor.py
setup.cfg
tests/data/edge_cases/24_star_arguments/numpy.py
tests/test_main.py

Closes https://github.com/jsh9/pydoclint/issues/121

Add new config option for documenting star arguments

---

CHANGELOG.md
README.md
docs/index.md
docs/violation_codes.md
pydoclint/flake8_entry.py
pydoclint/main.py
pydoclint/utils/return_yield_raise.py
pydoclint/utils/violation.py
pydoclint/visitor.py
tests/data/google/raises/cases.py
tests/data/numpy/raises/cases.py
tests/data/sphinx/raises/cases.py
tests/test_baseline.py
tests/test_main.py
tests/utils/test_returns_yields_raise.py

Addresses additional comments in https://github.com/jsh9/pydoclint/issues/213

New violation code D504

---

CHANGELOG.md
docs/config_options.md
pydoclint/flake8_entry.py
pydoclint/main.py
pydoclint/visitor.py
tests/data/edge_cases/25_underscore_and_private_args/cases.py
tests/test_main.py

Closes https://github.com/jsh9/pydoclint/issues/216

Add --ignore-private-args option

---

CHANGELOG.md
pydoclint/utils/return_anno.py
setup.cfg
tests/data/edge_cases/26_decompose_tuples/cases.py
tests/test_main.py

Fixes https://github.com/jsh9/pydoclint/issues/223

Fix a bug in decomposing tuples in docstrings

---

CHANGELOG.md
pydoclint/flake8_entry.py

Fixes https://github.com/jsh9/pydoclint/issues/216#issuecomment-2774217303

Fix typo in config option default value
